# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}

          # Options
          user: apwlq
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Seoul
          plugin_people: yes
          plugin_people_limit: 100
          plugin_people_size: 28
          plugin_people_types: followers, following
